remote_theme : "jeffreytse/jekyll-theme-yat"

title: Vanhiupun blog
email: fanxiaobin422@gamil.com
author: Vanhiupun

copyright: "著作权 (cleft) {currentYear} {author}"

description: >- # 这意味着在“baseurl:”之前忽略换行符
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # 您网站的子路径，例如 /blog
url: "" # 您站点的基本主机名和协议，例如 e.g. http://example.com
favicon: "./favicon.png" # 您网站的图标

yat:
  date_format: "%b %d, %Y"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  footnote_nr:    1

# Disqus 评论
disqus:
  shortname: "vanhiupun"

# 摘录大小设置
excerpt_size: 250

# 如果要生成网站站点地图，可以设置为true
sitemap: true

# 分页设置
paginate: 5

# 如果您只想链接标题中的特定页面，请取消注释
# 按顺序添加页面的路径
header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html
  - about.md

# Google Analytics
google_analytics: "UA-212989441-1"    # 你用Google账号去注册一个就会给你一个这样的id
enableDNT: "false"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-admin
  - rouge
  - jemoji
  - kramdown
