# theme: owner/name --> 不要忘记删除/注释基于 gem 的主题选项
remote_theme : " jeffreytse/jekyll-theme-yat "

title: Vanhiupun blog
email: fanxiaobin422@gamil.com
author: Vanhiupun

copyright: "版权所有 (cleft) {currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "https://img.icons8.com/windows/100/000000/coffee.png" # the favicon for your site

yat:
  date_format: "%b %d, %Y"

  markdown: kramdown
kmarkdown:
  input: GFM

# Pagination setting
paginate: 5

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-admin
